#include <stdio.h>
#include <time.h>

// Forces generation of inline code on Windows
__declspec(dllexport) void* funcs[] = {
    // stdio.h
    &fprintf,
    &fprintf_s,
    &fscanf,
    &fscanf_s,
    &fwprintf,
    &fwprintf_s,
    &fwscanf,
    &fwscanf_s,
    &printf,
    &printf_s,
    &scanf,
    &scanf_s,
    &snprintf,
    &sprintf,
    &sprintf_s,
    &sscanf,
    &sscanf_s,
    &swprintf,
    &swprintf_s,
    &swscanf,
    &swscanf_s,
    &vfprintf,
    &vfprintf_s,
    &vfscanf,
    &vfscanf_s,
    &vfwprintf,
    &vfwprintf_s,
    &vfwscanf,
    &vfwscanf_s,
    &vprintf,
    &vprintf_s,
    &vscanf,
    &vscanf_s,
    &vsnprintf,
    &vsnprintf_s,
    &vsprintf,
    &vsprintf_s,
    &vsscanf,
    &vsscanf_s,
    &vswprintf,
    &vswprintf_s,
    &vswscanf,
    &vswscanf_s,
    &vwprintf,
    &vwprintf_s,
    &vwscanf,
    &vwscanf_s,
    &wprintf,
    &wprintf_s,
    &wscanf,
    &wscanf_s,

    // time.h
    &gmtime
};
